### ISSUE TITLE
`ExecAsync` sometimes returns error for fast path transactions due to race condition

### ISSUE THREAD

**Issue by vilterp** [RelationalAI/rai-sdk-go#12]
**Repro**

1. Do a transaction with `Execute` which may hit the fast path

**Expected**

* If transaction hits the fast path, SDK returns results directly from `POST /transactions` response

**Actual**

* SDK returns a 400 "bad request, txn still running" error: https://relationalai.slack.com/archives/C02C9AV2LL9/p1658263705982599

**Diagnosis**

1. rai-server hits fast path; responds to `POST /transactions` with state `COMPLETED` and results (but hasn't finished writing the results to blob storage yet, or marked the txn completed in Consul yet… this is by design, to allow lower latency)
2. txn service forwards these results in its `POST /transactions` response to the Go SDK
3. Go SDK calls `GetTransactionResults`, assuming that since the txn is completed, the results must be there (shouldn't this code path check if the txn is aborted too?) https://github.com/RelationalAI/rai-sdk-go/blob/e5f70e84e03511e61047e0baf829f9d78410137c/rai/client.go#L1209-L1212
4. Txn service returns 400 because the txn is still marked as `RUNNING` in Consul
5. Later, rai-server finishes writing results to blob storage, and marks txn as `COMPLETED`

**Fix**

Do what the Julia SDK did: https://github.com/RelationalAI/rai-sdk-julia/pull/44

If the `POST /transactions` response comes back as completed or aborted, return the results that are attached to it.

cc @NHDaly @NRHelmi

**Comment by vilterp** [comment]
TODO: check for similar bugs in C# and Java SDKs

[https://github.com/RelationalAI/rai-sdk-java/blob/f1bfcdd0b4f61b6282ced785442bab730161554a/rai-sdk/src/main/java/com/relationalai/Client.java#L[…]45](https://github.com/RelationalAI/rai-sdk-java/blob/f1bfcdd0b4f61b6282ced785442bab730161554a/rai-sdk/src/main/java/com/relationalai/Client.java#L740-L745)
https://github.com/RelationalAI/rai-sdk-csharp/blob/9f6ba54b076804074d2584e29706d84f9b7edc25/RelationalAI/Client.cs#L477-L495

**Comment by NHDaly** [comment]
> If the POST /transactions response comes back as completed, return the results that are attached to it.

(completed or aborted, i think) 👍

**Comment by vilterp** [comment]
`ExecAsync` only appears to read the first part (JSON) of the multipart `POST /transactions` response: https://github.com/RelationalAI/rai-sdk-go/blob/e5f70e84e03511e61047e0baf829f9d78410137c/rai/client.go#L1197-L1199

Looks like we'll need to change it to parse out all the parts

**Comment by NHDaly** [comment]
After discussing on a call today, we think the most pragmatic solution is the following:
- disable the fast-path entirely
- simplify the logic to just always spin until GET /transactions/{id} from Infra returns COMPLETED / ABORTED

This way, we don't have to adjust `ExecAsync` to parse the multipart response.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6064](https://relationalai.atlassian.net/browse/RAI-6064).

_This link is only accessible to employees of RelationalAI._
