### ISSUE TITLE
Update changelog to match existing tags, then tag a new release

### ISSUE THREAD

**Issue by NHDaly** [RelationalAI/rai-sdk-go#23]

**Comment by NRHelmi** [comment]
changelog updated here https://github.com/RelationalAI/rai-sdk-go/commit/bbc1c3bba86b43865e983d992d48161e5652530f
added a new tag for the latest release

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6293](https://relationalai.atlassian.net/browse/RAI-6293).

_This link is only accessible to employees of RelationalAI._
