### ISSUE TITLE
SDK is not deleting the engine created by the tests

### ISSUE THREAD

**Issue by miazamrai** [RelationalAI/rai-sdk-go#50]
Tests are not deleting the engine created by the tests after completion, in case of failures.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-8113](https://relationalai.atlassian.net/browse/RAI-8113).

_This link is only accessible to employees of RelationalAI._
